name: Test
on:
  push:
    branches:
      - '**'

jobs:

  editorconfig-checker:
    name: ec
    uses: evoja/dependaboja/.github/workflows/editorconfig-checker.yaml@9fcead464c170975583ffe8eb3478d153a86d421
